import type { Metadata } from "next";
import { useRouter } from "next/router";
// import { Inter } from "next/font/google";
import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });
import { Auth } from "@/components/Auth";
export const metadata: Metadata = {
  title: "GashUp",
  description: "Generated by create next app",
};
//
import TopBar from "@/components/TopBar";
import SideBar from "@/components/SideBar";
import RightBar from "@/components/RightBar";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container relative">
        <TopBar />
        <div className="content flex flex-row">
          <SideBar />
          <div style={{ flex: 7 }} className="pt-2 pl-2 pr-2">
            {children}
          </div>
          <RightBar />
        </div>
      </body>
    </html>
  );
}
